feat(actions): combined seperate actions into a single workflow

diff --git a/.github/workflows/ci-workflows.yml b/.github/workflows/ci-workflows.yml
--- a/.github/workflows/ci-workflows.yml
+++ b/.github/workflows/ci-workflows.yml
@@ -11,6 +11,50 @@ on:
       - main
 
 jobs:
+  # Python Linting
+  lint:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.9'
+
+      - name: Install dependencies
+        run: pip install -r requirements.txt
+        working-directory: ./api
+
+      - name: Run linter
+        run: flake8 ./api
+
+  # Python unit tests
+  test:
+    if: github.event_name == 'push'
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.9'
+
+      - name: Install dependencies
+        run: pip install -r requirements.txt
+        working-directory: ./api
+
+      - name: Run tests
+        run: pytest
+        working-directory: ./api
+  
+  # Build Docker Image and publish to repo
   build:
     if: github.event_name == 'push'
     runs-on: ubuntu-latest
@@ -40,44 +84,64 @@ jobs:
         context: "{{defaultContext}}:api"
         push: true
         tags: ${{ steps.meta.outputs.tags }}
-
-  lint:
-    if: github.event_name == 'push'
+  
+  # Deploy terraform infrastructure
+  deploy:
     runs-on: ubuntu-latest
+    permissions:
+      id-token: write
+      contents: read
+    env:
+      TF_LOG: INFO #for getting logs in case of error
+      TF_INPUT: false #disables user inputs
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+    defaults:
+      run:
+        shell: bash
+        working-directory: ./infrastructure
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
+    steps: 
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: 'Azure Login'
+        uses: azure/login@v2
         with:
-          python-version: '3.9'
+          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
 
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-        working-directory: ./api
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v3
+      
+      - name: Terraform init
+        id: init
+        run: |
+          terraform init \
+          -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
+          -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
+          -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
+          -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" 
+        #giving backend config to access Azure State storage 
+      
+      - name: Terraform Format
+        run: terraform fmt -check #checks formatting
 
-      - name: Run linter
-        run: flake8 ./api
+      - name: Terraform Validate
+        # Run even if formatting fails
+        if: success() || failure()
+        run: terraform validate -no-color #checks syntax
 
-  test:
-    if: github.event_name == 'push'
-    runs-on: ubuntu-latest
+        #Plan section
+      - name: Generate and Show Plan
+        id: plan
+        if: success() || failure()
+        run: |
+          echo "Terraform Plan Output:"
+          echo "-------------------"
+          terraform plan -var="subscription_id"=${{ secrets.AZURE_SUBSCRIPTION_ID }} -var="otel_exporter_otlp_headers=${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}" -no-color -out=build.tfplan
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
-
-      - name: Install dependencies
-        run: pip install -r requirements.txt
-        working-directory: ./api
-
-      - name: Run tests
-        run: pytest
-        working-directory: ./api
+        #Apply section
+      - name: Terraform Apply
+        id: apply
+        continue-on-error: true
+        if: steps.plan.outcome == 'success'
+        run: terraform apply -auto-approve -input=false -no-color build.tfplan
